POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBldHRlcmkiLCJpZCI6IjYzYjZlY2NhNjk1YTllMGM3MzM5NGM1ZSIsImlhdCI6MTY3MjkzMjU4OX0.j5cxzvni0qcJ66xDvG-VD4qHZN9chxzJADw5LoZSSx0

{
    "title": "LISÄ",
    "author": "KALLE",
    "url": "www.jjjw",
    "likes": 10,
    "userId": "63b6ecca695a9e0c73394c5e"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Petteri",
    "password": "lolli"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Petteri",
    "password": "lolli"
}

###

PUT http://localhost:3003/api/blogs/63b6ed0b695a9e0c73394c63
Content-Type: application/json

{
    "title": "petterimaa",
"url": "www.jjjw",
"author": "Liisaeri",
"likes": 99,
}